from typing import Any, Dict, List, Optional


ExternalTemplate = Dict[str, Any]


def _template(
    *,
    id: str,
    category: str,
    name: str,
    description: str,
    provider: str,
    source_url: str,
    preview_sections: List[str],
    tags: Optional[List[str]] = None,
    rating: float = 4.8,
) -> ExternalTemplate:
    return {
        "id": f"external_{id}",
        "user_id": None,
        "name": name,
        "category": category,
        "description": description,
        "thumbnail_url": None,
        "visibility": "public",
        "author_name": provider,
        "usage_count": 0,
        "rating": rating,
        "tags": tags or [],
        "is_system": False,
        "is_public": True,
        "is_external": True,
        "source_url": source_url,
        "preview_sections": preview_sections,
        "created_at": "2026-08-22T00:00:00Z",
    }


EXTERNAL_TEMPLATE_CATALOG: List[ExternalTemplate] = [
    _template(
        id="business_microsoft_plan",
        category="business",
        name="Business Plan",
        description="Mẫu kế hoạch kinh doanh có phần thị trường, tài chính, checklist triển khai và startup checklist.",
        provider="Microsoft Support",
        source_url="https://support.microsoft.com/en-us/office/create-a-business-plan",
        tags=["word", "business-plan", "startup"],
        preview_sections=["Tóm tắt điều hành", "Phân tích thị trường", "Kế hoạch tài chính", "Checklist triển khai"],
    ),
    _template(
        id="business_canva_planning",
        category="business",
        name="Professional Business Planning Report",
        description="Mẫu báo cáo lập kế hoạch kinh doanh trên Canva, phù hợp cho chiến lược và roadmap.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/",
        tags=["report", "planning", "canva"],
        preview_sections=["Trang bìa", "Mục tiêu kinh doanh", "Roadmap", "Chỉ số đánh giá"],
    ),
    _template(
        id="business_smartsheet_brd",
        category="business",
        name="Business Requirements Document",
        description="Bộ mẫu BRD cho yêu cầu nghiệp vụ, phạm vi, rủi ro và phương án đề xuất.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/content/business-requirement-document-templates",
        tags=["brd", "requirements", "project"],
        preview_sections=["Mục tiêu nghiệp vụ", "Phạm vi", "Yêu cầu chức năng", "Rủi ro và ngoại lệ"],
    ),
    _template(
        id="business_canva_annual",
        category="business",
        name="Corporate Annual Report",
        description="Mẫu báo cáo thường niên doanh nghiệp với phần tổng quan, hiệu suất và kế hoạch năm tới.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/",
        tags=["annual-report", "corporate"],
        preview_sections=["Thông điệp lãnh đạo", "Hiệu suất năm", "Sáng kiến chính", "Kế hoạch tiếp theo"],
    ),
    _template(
        id="financial_canva_annual",
        category="financial",
        name="Annual Financial Report",
        description="Mẫu báo cáo tài chính thường niên để trình bày kết quả, dòng tiền và nhận định quản trị.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/",
        tags=["financial", "annual", "canva"],
        preview_sections=["Tổng quan tài chính", "Doanh thu và chi phí", "Dòng tiền", "Nhận định quản trị"],
    ),
    _template(
        id="financial_canva_finance_presentation",
        category="financial",
        name="Financial Analysis Presentation",
        description="Bộ slide tài chính để kể câu chuyện số liệu, KPI và các điểm cần ra quyết định.",
        provider="Canva",
        source_url="https://www.canva.com/presentations/templates/finance/",
        tags=["finance", "presentation", "kpi"],
        preview_sections=["Executive summary", "KPI chính", "Phân tích biến động", "Khuyến nghị"],
    ),
    _template(
        id="financial_smartsheet_budget_dashboard",
        category="financial",
        name="Budget Dashboard",
        description="Mẫu dashboard ngân sách theo dõi kế hoạch, thực tế, chênh lệch và tiến độ chi tiêu.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-excel-dashboard-templates",
        tags=["excel", "budget", "dashboard"],
        preview_sections=["Ngân sách kế hoạch", "Chi phí thực tế", "Chênh lệch", "Cảnh báo vượt ngưỡng"],
    ),
    _template(
        id="financial_canva_q4",
        category="financial",
        name="Q4 Financial Report",
        description="Mẫu báo cáo tài chính quý cho tổng hợp hiệu suất, dự báo và phân tích xu hướng.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/",
        tags=["quarterly", "finance", "report"],
        preview_sections=["Kết quả quý", "So sánh kế hoạch", "Dự báo", "Việc cần làm"],
    ),
    _template(
        id="technical_smartsheet_it_spec",
        category="technical",
        name="IT Technical Specification",
        description="Mẫu đặc tả kỹ thuật IT cho hạ tầng, nâng cấp hệ thống và dự án kỹ thuật.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-technical-specification-templates",
        tags=["technical-spec", "it", "excel"],
        preview_sections=["Tổng quan dự án", "Yêu cầu kỹ thuật", "Tài nguyên cần thiết", "Tiêu chí nghiệm thu"],
    ),
    _template(
        id="technical_smartsheet_website_spec",
        category="technical",
        name="Website Technical Specification",
        description="Mẫu đặc tả website gồm điều hướng, CMS, thiết kế, bảo mật và tracking yêu cầu.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-technical-specification-templates",
        tags=["website", "requirements", "security"],
        preview_sections=["Mục tiêu website", "Luồng người dùng", "Yêu cầu CMS", "Yêu cầu bảo mật"],
    ),
    _template(
        id="technical_smartsheet_software_spec",
        category="technical",
        name="Software Technical Specification",
        description="Mẫu Word đặc tả phần mềm với phạm vi, tính năng, giao diện và phụ thuộc hệ thống.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-technical-specification-templates",
        tags=["software", "word", "architecture"],
        preview_sections=["Phạm vi sản phẩm", "Tính năng hệ thống", "Giao diện", "Giả định và phụ thuộc"],
    ),
    _template(
        id="technical_template_net_spec",
        category="technical",
        name="Technical Specification Template",
        description="Mẫu đặc tả kỹ thuật có định dạng Word và Google Docs, dễ chỉnh sửa và in ấn.",
        provider="Template.net",
        source_url="https://www.template.net/editable/107306/technical-specification",
        tags=["word", "google-docs", "specification"],
        preview_sections=["Thông tin tài liệu", "Yêu cầu", "Thiết kế kỹ thuật", "Phê duyệt"],
    ),
    _template(
        id="academic_canva_thesis",
        category="academic",
        name="Thesis Defense Presentation",
        description="Mẫu trình bày luận văn/khóa luận với phương pháp, kết quả và kết luận nghiên cứu.",
        provider="Canva",
        source_url="https://www.canva.com/presentations/templates/research/",
        tags=["thesis", "presentation", "academic"],
        preview_sections=["Vấn đề nghiên cứu", "Phương pháp", "Kết quả", "Kết luận"],
    ),
    _template(
        id="academic_canva_research_cover",
        category="academic",
        name="Research Paper Cover Page",
        description="Mẫu trang bìa bài nghiên cứu dùng cho báo cáo học thuật và bài tập lớn.",
        provider="Canva",
        source_url="https://www.canva.com/templates/s/research/",
        tags=["cover", "paper", "student"],
        preview_sections=["Tiêu đề", "Tác giả", "Đơn vị", "Thông tin môn học"],
    ),
    _template(
        id="academic_local_bach_khoa",
        category="academic",
        name="Mẫu Báo cáo Bài tập lớn CNTT - ĐH Bách Khoa Hà Nội",
        description="Mẫu học thuật A4, Times New Roman, bố cục chương mục phù hợp bài tập lớn CNTT.",
        provider="AI Report Studio",
        source_url="https://hust.edu.vn/",
        tags=["academic", "vietnam", "docx"],
        preview_sections=["Trang bìa", "Lời mở đầu", "Chương 1-5", "Tài liệu tham khảo"],
    ),
    _template(
        id="academic_canva_project",
        category="academic",
        name="Modern Research Project Presentation",
        description="Mẫu thuyết trình dự án nghiên cứu dành cho sinh viên và nhóm nghiên cứu.",
        provider="Canva",
        source_url="https://www.canva.com/presentations/templates/research/",
        tags=["student", "research", "slides"],
        preview_sections=["Mục tiêu", "Phương pháp", "Phát hiện chính", "Hướng phát triển"],
    ),
    _template(
        id="research_canva_market",
        category="research",
        name="Market Research Report",
        description="Mẫu nghiên cứu thị trường để trình bày phương pháp, insight và chân dung khách hàng.",
        provider="Canva",
        source_url="https://www.canva.com/templates/s/research/",
        tags=["market-research", "analysis"],
        preview_sections=["Bối cảnh thị trường", "Phương pháp khảo sát", "Insight", "Khuyến nghị"],
    ),
    _template(
        id="research_canva_services",
        category="research",
        name="Market Research and Analysis Services",
        description="Mẫu giới thiệu dịch vụ nghiên cứu, phù hợp cho đề xuất nghiên cứu khách hàng.",
        provider="Canva",
        source_url="https://www.canva.com/templates/s/research/",
        tags=["services", "research", "proposal"],
        preview_sections=["Mục tiêu nghiên cứu", "Phạm vi dịch vụ", "Phương pháp", "Đầu ra"],
    ),
    _template(
        id="research_canva_mars",
        category="research",
        name="Mars Research Report",
        description="Mẫu báo cáo nghiên cứu chủ đề khoa học với cấu trúc trình bày phát hiện rõ ràng.",
        provider="Canva",
        source_url="https://www.canva.com/templates/s/research/",
        tags=["science", "report"],
        preview_sections=["Câu hỏi nghiên cứu", "Dữ liệu", "Phân tích", "Kết luận"],
    ),
    _template(
        id="research_canva_ocean",
        category="research",
        name="Ocean Animal Report Worksheet",
        description="Mẫu worksheet báo cáo nghiên cứu, phù hợp cho bài nghiên cứu ngắn có cấu trúc.",
        provider="Canva",
        source_url="https://www.canva.com/templates/s/research/",
        tags=["worksheet", "education"],
        preview_sections=["Đối tượng nghiên cứu", "Đặc điểm", "Môi trường", "Tổng kết"],
    ),
    _template(
        id="data_smartsheet_kpi_dashboard",
        category="data",
        name="KPI Performance Dashboard",
        description="Mẫu dashboard KPI Excel để theo dõi nhiệm vụ, rủi ro, vấn đề và doanh thu.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-excel-dashboard-templates",
        tags=["kpi", "excel", "dashboard"],
        preview_sections=["Tổng quan KPI", "Tiến độ", "Rủi ro", "Doanh thu tháng/quý"],
    ),
    _template(
        id="data_smartsheet_project_dashboard",
        category="data",
        name="Project Management Dashboard",
        description="Mẫu dashboard quản lý dự án với timeline, trạng thái nhiệm vụ và biểu đồ ngân sách.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-excel-dashboard-templates",
        tags=["project", "dashboard", "excel"],
        preview_sections=["Timeline", "Trạng thái nhiệm vụ", "Ưu tiên", "Ngân sách"],
    ),
    _template(
        id="data_smartsheet_quality_dashboard",
        category="data",
        name="Data Quality Dashboard",
        description="Mẫu dashboard chất lượng dữ liệu theo dõi chỉ số đầy đủ, hợp lệ và sai lệch.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-excel-dashboard-templates",
        tags=["data-quality", "metrics"],
        preview_sections=["Độ đầy đủ", "Độ hợp lệ", "Lỗi dữ liệu", "Xu hướng chất lượng"],
    ),
    _template(
        id="data_smartsheet_product_metrics",
        category="data",
        name="Product Metrics Dashboard",
        description="Mẫu dashboard sản phẩm theo dõi doanh thu, phân phối và hiệu suất theo mặt hàng.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-excel-dashboard-templates",
        tags=["product", "metrics", "dashboard"],
        preview_sections=["Doanh thu sản phẩm", "Tỷ trọng", "Time to market", "Hiệu suất"],
    ),
    _template(
        id="proposal_smartsheet_simple",
        category="proposal",
        name="Simple Project Proposal",
        description="Mẫu đề xuất dự án có lịch trình, ngân sách, đội ngũ và nhu cầu nguồn lực.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/content/project-request-form-templates",
        tags=["proposal", "project", "word"],
        preview_sections=["Tóm tắt đề xuất", "Lịch trình", "Ngân sách", "Nguồn lực"],
    ),
    _template(
        id="proposal_smartsheet_approval",
        category="proposal",
        name="Simple Project Approval Form",
        description="Mẫu phê duyệt dự án với mục tiêu, lợi ích, lịch trình, ngân sách và chữ ký.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/content/project-approval-forms-templates",
        tags=["approval", "proposal"],
        preview_sections=["Thông tin dự án", "Kết quả mong muốn", "Ngân sách", "Phê duyệt"],
    ),
    _template(
        id="proposal_canva_campaign",
        category="proposal",
        name="Campaign Proposal Presentation",
        description="Mẫu đề xuất chiến dịch marketing dạng presentation để trình bày mục tiêu và kế hoạch.",
        provider="Canva",
        source_url="https://www.canva.com/collection/marketing/",
        tags=["campaign", "proposal", "slides"],
        preview_sections=["Mục tiêu chiến dịch", "Đối tượng", "Kế hoạch triển khai", "Ngân sách"],
    ),
    _template(
        id="proposal_canva_business",
        category="proposal",
        name="Business Proposal Presentation",
        description="Mẫu proposal doanh nghiệp để trình bày cơ hội, giải pháp, timeline và chi phí.",
        provider="Canva",
        source_url="https://www.canva.com/presentations/templates/finance/",
        tags=["business", "proposal"],
        preview_sections=["Cơ hội", "Giải pháp", "Timeline", "Chi phí"],
    ),
    _template(
        id="marketing_canva_report",
        category="marketing",
        name="Marketing Report",
        description="Mẫu báo cáo marketing để trình bày dữ liệu chiến dịch, insight và đề xuất tối ưu.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/marketing/",
        tags=["marketing", "report"],
        preview_sections=["Tổng quan chiến dịch", "Kênh truyền thông", "KPI", "Đề xuất"],
    ),
    _template(
        id="marketing_canva_social",
        category="marketing",
        name="Social Media Content Performance Report",
        description="Mẫu báo cáo hiệu suất nội dung mạng xã hội theo reach, engagement và chuyển đổi.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/marketing/",
        tags=["social-media", "performance"],
        preview_sections=["Kênh", "Reach", "Engagement", "Bài học"],
    ),
    _template(
        id="marketing_canva_campaign_calendar",
        category="marketing",
        name="Marketing Campaign Calendar Report",
        description="Mẫu lịch chiến dịch marketing để theo dõi nội dung, thời điểm và trách nhiệm.",
        provider="Canva",
        source_url="https://www.canva.com/collection/marketing/",
        tags=["calendar", "campaign"],
        preview_sections=["Lịch chiến dịch", "Nội dung", "Người phụ trách", "Trạng thái"],
    ),
    _template(
        id="marketing_canva_strategy",
        category="marketing",
        name="Retail Marketing Strategy Report",
        description="Mẫu báo cáo chiến lược marketing bán lẻ với phân khúc, thông điệp và kênh.",
        provider="Canva",
        source_url="https://www.canva.com/collection/marketing/",
        tags=["retail", "strategy"],
        preview_sections=["Phân khúc", "Thông điệp", "Kênh", "Dự báo tác động"],
    ),
    _template(
        id="operations_canva_daily",
        category="operations",
        name="Daily Project Status Report",
        description="Mẫu báo cáo ngày để theo dõi công việc, tiến độ và vấn đề vận hành.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/daily/",
        tags=["daily", "status", "operations"],
        preview_sections=["Việc đã hoàn thành", "Việc đang làm", "Vấn đề", "Việc ngày mai"],
    ),
    _template(
        id="operations_smartsheet_request",
        category="operations",
        name="Project Request Form",
        description="Mẫu yêu cầu dự án để chuẩn hóa thông tin đầu vào, lợi ích, ngân sách và nguồn lực.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/content/project-request-form-templates",
        tags=["request", "operations"],
        preview_sections=["Thông tin yêu cầu", "Lợi ích", "Ngân sách", "Nguồn lực"],
    ),
    _template(
        id="operations_smartsheet_portfolio",
        category="operations",
        name="Project Portfolio Dashboard",
        description="Mẫu dashboard danh mục dự án để theo dõi nhiều timeline, rủi ro và phân bổ nguồn lực.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/free-excel-dashboard-templates",
        tags=["portfolio", "dashboard"],
        preview_sections=["Danh mục dự án", "Timeline", "Rủi ro", "Nguồn lực"],
    ),
    _template(
        id="operations_canva_work",
        category="operations",
        name="Daily Work Report",
        description="Mẫu báo cáo công việc hằng ngày cho đội vận hành, hiện trường hoặc back-office.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/daily/",
        tags=["daily-work", "team"],
        preview_sections=["Nhiệm vụ", "Thời gian", "Trở ngại", "Ghi chú"],
    ),
    _template(
        id="custom_canva_blank_report",
        category="custom",
        name="Blank Report",
        description="Mẫu báo cáo trống trên Canva để tự xây dựng bố cục theo thương hiệu riêng.",
        provider="Canva",
        source_url="https://www.canva.com/reports/templates/",
        tags=["blank", "custom"],
        preview_sections=["Trang bìa", "Mục lục", "Nội dung tùy chỉnh", "Kết luận"],
    ),
    _template(
        id="custom_canva_report_maker",
        category="custom",
        name="Custom Report Maker",
        description="Trình tạo report từ thư viện mẫu Canva để tùy biến theo ngành, màu sắc và bố cục.",
        provider="Canva",
        source_url="https://www.canva.com/create/reports/",
        tags=["custom", "builder"],
        preview_sections=["Chọn mẫu", "Tùy biến nội dung", "Thêm biểu đồ", "Xuất bản"],
    ),
    _template(
        id="custom_template_net_word",
        category="custom",
        name="Editable Word Template",
        description="Mẫu Word/Google Docs có thể chỉnh sửa để dùng làm nền cho tài liệu tùy chỉnh.",
        provider="Template.net",
        source_url="https://www.template.net/editable/107306/technical-specification",
        tags=["word", "google-docs", "editable"],
        preview_sections=["Thông tin tài liệu", "Nội dung chính", "Phụ lục", "Phê duyệt"],
    ),
    _template(
        id="custom_smartsheet_form",
        category="custom",
        name="Custom Project Request Template",
        description="Mẫu form yêu cầu dự án có thể điều chỉnh cho quy trình nội bộ riêng.",
        provider="Smartsheet",
        source_url="https://www.smartsheet.com/content/project-request-form-templates",
        tags=["form", "custom", "workflow"],
        preview_sections=["Trường tùy chỉnh", "Người phụ trách", "Trạng thái", "Phê duyệt"],
    ),
]


def list_external_templates(category: Optional[str] = None, search: Optional[str] = None) -> List[ExternalTemplate]:
    items = EXTERNAL_TEMPLATE_CATALOG
    if category and category.lower() != "all":
        items = [item for item in items if item["category"] == category.lower()]

    if search:
        normalized = search.lower().strip()
        items = [
            item
            for item in items
            if normalized in item["name"].lower()
            or normalized in item["description"].lower()
            or normalized in item["provider"].lower()
            or any(normalized in tag.lower() for tag in item.get("tags", []))
        ]

    return [dict(item) for item in items]
